/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description 读取全部设置，敏感字段自动 mask。
         *
         *     返回:
         *         包含全部已存设置的字典；``emby.api_key`` 等敏感字段为 mask 形式。
         */
        get: operations["get_settings_api_v1_settings_get"];
        /**
         * Put Settings
         * @description 整体覆盖式写入设置。
         *
         *     遍历请求体里的 key→value 写入 DB（upsert），写完显式 commit 以保证
         *     请求结束关闭 session 前数据落库。
         *
         *     参数:
         *         body: 客户端提交的 key→value 字典，支持 dict / list / str / int / bool。
         *         service: 注入的设置服务实例。
         *         db: 与 service 共享的 session，用于显式 commit。
         *
         *     返回:
         *         写入后的全量设置（敏感字段已 mask）。
         */
        put: operations["put_settings_api_v1_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/emby/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Emby Connection
         * @description 测试给定的 Emby 服务是否可达。
         *
         *     参数:
         *         body: 包含 ``server_url`` 与 ``api_key`` 的请求体。
         *
         *     返回:
         *         - 成功：``{success: true, message: "连接成功"}``；
         *         - 鉴权失败：``{success: false, message: "API Key 无效"}``；
         *         - 连接失败：``{success: false, message: "连接失败"}``；
         *         - 未预期异常：500 + 错误体。
         *
         *     说明:
         *         鉴权/连接失败仍返回 200 + ``success=false``，避免前端按 HTTP 状态
         *         码区分业务失败与系统故障。
         */
        post: operations["test_emby_connection_api_v1_emby_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/emby/libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Libraries
         * @description 获取 Emby 媒体库列表。
         *
         *     返回:
         *         未配置 Emby → 400 + 错误体；成功 → ``[EmbyLibrary, ...]``。
         */
        get: operations["get_libraries_api_v1_emby_libraries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/emby/series/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Series
         * @description 按关键字搜索 Emby 剧集。
         */
        get: operations["search_series_api_v1_emby_series_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/emby/series/{series_id}/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Series Seasons
         * @description 获取指定剧集的季列表。
         */
        get: operations["get_series_seasons_api_v1_emby_series__series_id__seasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/emby/series/{series_id}/seasons/{season_number}/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Series Episodes
         * @description 获取指定剧集指定季的分集列表。
         */
        get: operations["get_series_episodes_api_v1_emby_series__series_id__seasons__season_number__episodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/emby/series/{series_id}/seasons/{season_number}/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Series Latest Episode
         * @description 推断指定剧集指定季的下一可用集号。
         *
         *     返回:
         *         - 未配置 Emby → 400；
         *         - 季内无分集 → ``{latest_episode: 0, next_episode: 1}``；
         *         - 有分集 → ``{latest_episode: max, next_episode: max + 1}``。
         */
        get: operations["get_series_latest_episode_api_v1_emby_series__series_id__seasons__season_number__latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Libraries
         * @description 列出全部媒体库。
         *
         *     返回:
         *         按主键升序的所有媒体库。
         */
        get: operations["list_libraries_api_v1_libraries_get"];
        put?: never;
        /**
         * Create Library
         * @description 创建媒体库。
         *
         *     参数:
         *         body: 创建请求载荷，``name`` / ``staging_root`` / ``target_root`` 必填。
         *         db: 与 ``service`` 共享的 session，用于 commit。
         *         service: 注入的设置服务，用于读取 ``file.allowed_browse_roots``。
         *
         *     返回:
         *         新建媒体库的响应载荷。
         *
         *     抛出:
         *         HTTPException: 路径越界时返回 400。
         */
        post: operations["create_library_api_v1_libraries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/libraries/{library_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Library
         * @description 读取单个媒体库详情。
         *
         *     参数:
         *         library_id: 媒体库主键。
         *         db: 数据库会话。
         *
         *     返回:
         *         媒体库响应载荷。
         *
         *     抛出:
         *         HTTPException: 不存在时返回 404。
         */
        get: operations["get_library_api_v1_libraries__library_id__get"];
        /**
         * Update Library
         * @description 更新媒体库。
         *
         *     只把请求体中非空的字段写到 ORM 对象上；任一路径字段被覆盖时先做
         *     ``safe_resolve`` 校验，校验失败抛 400 且不改 DB。
         *
         *     参数:
         *         library_id: 待更新的媒体库主键。
         *         body: 更新请求载荷，字段全部可选。
         *         db: 数据库会话。
         *         service: 注入的设置服务，用于读取 ``file.allowed_browse_roots``。
         *
         *     返回:
         *         更新后的媒体库响应载荷。
         *
         *     抛出:
         *         HTTPException: 不存在 404；路径越界 400。
         */
        put: operations["update_library_api_v1_libraries__library_id__put"];
        post?: never;
        /**
         * Delete Library
         * @description 删除媒体库。
         *
         *     不做级联删除关联 series（由后续任务处理）；id 不存在时返回 404。
         *
         *     参数:
         *         library_id: 待删除的媒体库主键。
         *         db: 数据库会话。
         *
         *     返回:
         *         204 No Content。
         *
         *     抛出:
         *         HTTPException: 不存在时返回 404。
         */
        delete: operations["delete_library_api_v1_libraries__library_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Series
         * @description 列出全部剧集，可选按 ``library_id`` 过滤。
         *
         *     参数:
         *         library_id: 可选过滤参数；为空时返回全部。
         *         db: 数据库会话。
         *
         *     返回:
         *         按主键升序的 series 列表。
         */
        get: operations["list_series_api_v1_series_get"];
        put?: never;
        /**
         * Create Series
         * @description 创建剧集。
         *
         *     参数:
         *         body: 创建请求载荷。
         *         db: 数据库会话。
         *
         *     返回:
         *         新建剧集响应载荷。
         *
         *     抛出:
         *         HTTPException: library 不存在或路径越界时返回 400。
         */
        post: operations["create_series_api_v1_series_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{series_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Series
         * @description 读取单个剧集详情。
         *
         *     参数:
         *         series_id: 剧集主键。
         *         db: 数据库会话。
         *
         *     返回:
         *         剧集响应载荷。
         *
         *     抛出:
         *         HTTPException: 不存在时返回 404。
         */
        get: operations["get_series_api_v1_series__series_id__get"];
        /**
         * Update Series
         * @description 更新剧集。
         *
         *     只把请求体中显式传入的字段写到 ORM 对象上；任一路径字段被覆盖时，用
         *     effective library_id（请求体未传则取 series 当前值）做 ``safe_resolve``
         *     校验，失败抛 400。
         *
         *     参数:
         *         series_id: 待更新的剧集主键。
         *         body: 更新请求载荷。
         *         db: 数据库会话。
         *
         *     返回:
         *         更新后的剧集响应载荷。
         *
         *     抛出:
         *         HTTPException: 不存在 404；library / 路径越界 400。
         */
        put: operations["update_series_api_v1_series__series_id__put"];
        post?: never;
        /**
         * Delete Series
         * @description 删除剧集。
         *
         *     不做级联删除关联 tasks（由后续任务处理）；id 不存在时返回 404。
         *
         *     参数:
         *         series_id: 待删除的剧集主键。
         *         db: 数据库会话。
         *
         *     返回:
         *         204 No Content。
         *
         *     抛出:
         *         HTTPException: 不存在时返回 404。
         */
        delete: operations["delete_series_api_v1_series__series_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tasks
         * @description 列出任务，支持状态与剧集过滤。
         */
        get: operations["list_tasks_api_v1_tasks_get"];
        put?: never;
        /**
         * Create Task
         * @description 创建任务。
         */
        post: operations["create_task_api_v1_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Task
         * @description 预览任务路径，不入库。
         */
        post: operations["preview_task_api_v1_tasks_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task
         * @description 读取任务详情。
         */
        get: operations["get_task_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Task
         * @description 删除允许状态的任务。
         */
        delete: operations["delete_task_api_v1_tasks__task_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/nfo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Task Nfo
         * @description 更新任务 NFO，并重写 staging NFO 文件。
         */
        put: operations["update_task_nfo_api_v1_tasks__task_id__nfo_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/cover/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Task Cover
         * @description 上传封面到 staging。
         */
        post: operations["upload_task_cover_api_v1_tasks__task_id__cover_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/cover/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Download Task Cover
         * @description 下载封面到 staging。
         */
        post: operations["download_task_cover_api_v1_tasks__task_id__cover_download_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Commit Task
         * @description 提交任务到目标目录。
         */
        post: operations["commit_task_api_v1_tasks__task_id__commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/browse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Browse Files
         * @description 浏览目录。
         */
        post: operations["browse_files_api_v1_files_browse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate File
         * @description 校验源视频文件。
         */
        post: operations["validate_file_api_v1_files_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 健康检查端点。
         *
         *     返回三项状态：
         *     - ``status``: 进程级存活标志，固定 ``ok``。
         *     - ``db_ok``: settings DB 是否可达，异常时降级为 ``False``。
         *     - ``emby_configured``: Emby server_url / api_key / auto_refresh 三件套
         *       是否齐全，缺失则 ``False``。
         *
         *     DB 不可达时仍返回 200，避免监控把数据库抖动误判成进程级宕机。
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_task_cover_api_v1_tasks__task_id__cover_upload_post */
        Body_upload_task_cover_api_v1_tasks__task_id__cover_upload_post: {
            /** File */
            file: string;
        };
        /**
         * CoverDownloadRequest
         * @description 封面下载请求。
         */
        CoverDownloadRequest: {
            /** Cover Url */
            cover_url: string;
        };
        /**
         * EmbyTestRequest
         * @description ``POST /emby/test`` 请求载荷。
         *
         *     Attributes:
         *         server_url: Emby 服务器根地址。
         *         api_key: Emby API Key。
         */
        EmbyTestRequest: {
            /** Server Url */
            server_url: string;
            /** Api Key */
            api_key: string;
        };
        /**
         * EmbyTestResponse
         * @description ``POST /emby/test`` 响应载荷。
         *
         *     Attributes:
         *         success: 是否连接成功。
         *         message: 中文提示消息。
         *         server_name: Emby 服务名（保留字段，目前不强制填充）。
         */
        EmbyTestResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
            /** Server Name */
            server_name?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LatestEpisodeResponse
         * @description 下一集号推断响应。
         *
         *     Attributes:
         *         latest_episode: 当前最大集号；季内无任何分集时为 0。
         *         next_episode: 应使用的下一集号，``latest_episode + 1``；季内无分集时为 1。
         */
        LatestEpisodeResponse: {
            /** Latest Episode */
            latest_episode: number;
            /** Next Episode */
            next_episode: number;
        };
        /**
         * LibraryCreate
         * @description ``POST /api/v1/libraries`` 请求载荷。
         *
         *     Attributes:
         *         enabled: 是否启用该媒体库；默认 ``True``。
         */
        LibraryCreate: {
            /** Name */
            name: string;
            /** Collection Type */
            collection_type?: string | null;
            /** Staging Root */
            staging_root: string;
            /** Target Root */
            target_root: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /**
         * LibraryResponse
         * @description ``GET / POST / PUT /api/v1/libraries`` 响应载荷。
         *
         *     Attributes:
         *         id: 数据库主键。
         *         emby_library_id: Emby 侧 Library ID（未关联时为空）。
         *         name: 媒体库展示名。
         *         collection_type: 媒体库类型。
         *         staging_root: 整理缓存根目录。
         *         target_root: 目标根目录。
         *         enabled: 是否启用。
         *         created_at: 创建时间。
         *         updated_at: 最后更新时间。
         */
        LibraryResponse: {
            /** Id */
            id: number;
            /** Emby Library Id */
            emby_library_id: string | null;
            /** Name */
            name: string;
            /** Collection Type */
            collection_type: string | null;
            /** Staging Root */
            staging_root: string | null;
            /** Target Root */
            target_root: string | null;
            /** Enabled */
            enabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * LibraryUpdate
         * @description ``PUT /api/v1/libraries/{id}`` 请求载荷。
         *
         *     所有字段可选；调用方按需传入需要修改的字段，未传字段保持原值。
         */
        LibraryUpdate: {
            /** Name */
            name?: string | null;
            /** Collection Type */
            collection_type?: string | null;
            /** Staging Root */
            staging_root?: string | null;
            /** Target Root */
            target_root?: string | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /**
         * NFOUpdateRequest
         * @description NFO 更新请求。
         */
        NFOUpdateRequest: {
            /** Nfo Json */
            nfo_json: {
                [key: string]: unknown;
            };
        };
        /**
         * PathRequest
         * @description 单路径请求体。
         */
        PathRequest: {
            /** Path */
            path: string;
        };
        /**
         * SeriesCreate
         * @description ``POST /api/v1/series`` 请求载荷。
         *
         *     Attributes:
         *         enabled: 是否启用该 series；默认 ``True``。
         */
        SeriesCreate: {
            /** Name */
            name: string;
            /** Library Id */
            library_id?: number | null;
            /** Emby Series Id */
            emby_series_id?: string | null;
            /** Staging Path */
            staging_path?: string | null;
            /** Target Path */
            target_path?: string | null;
            /**
             * Default Season
             * @default 1
             */
            default_season: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /**
         * SeriesResponse
         * @description ``GET / POST / PUT /api/v1/series`` 响应载荷。
         *
         *     Attributes:
         *         id: 数据库主键。
         *         emby_series_id: Emby 侧 Series ID。
         *         name: 剧集展示名。
         *         library_id: 关联的媒体库主键。
         *         library_name: 关联媒体库名称（冗余字段，便于列表展示）。
         *         staging_path: 整理缓存路径。
         *         target_path: 目标路径。
         *         default_season: 默认季号。
         *         enabled: 是否启用。
         *         created_at: 创建时间。
         *         updated_at: 最后更新时间。
         */
        SeriesResponse: {
            /** Id */
            id: number;
            /** Emby Series Id */
            emby_series_id: string | null;
            /** Name */
            name: string;
            /** Library Id */
            library_id: number | null;
            /** Library Name */
            library_name: string | null;
            /** Staging Path */
            staging_path: string | null;
            /** Target Path */
            target_path: string | null;
            /** Default Season */
            default_season: number;
            /** Enabled */
            enabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SeriesUpdate
         * @description ``PUT /api/v1/series/{id}`` 请求载荷。
         *
         *     所有字段可选；调用方按需传入需要修改的字段，未传字段保持原值。
         */
        SeriesUpdate: {
            /** Name */
            name?: string | null;
            /** Library Id */
            library_id?: number | null;
            /** Emby Series Id */
            emby_series_id?: string | null;
            /** Staging Path */
            staging_path?: string | null;
            /** Target Path */
            target_path?: string | null;
            /** Default Season */
            default_season?: number | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /**
         * SettingsResponse
         * @description 设置响应载荷 - 整体是一个 key→value 字典（敏感字段已被 mask）。
         */
        SettingsResponse: {
            [key: string]: unknown;
        };
        /**
         * SettingsUpdateRequest
         * @description 设置更新请求载荷 - 整体是一个 key→value 字典。
         */
        SettingsUpdateRequest: {
            [key: string]: unknown;
        };
        /**
         * TaskCreateRequest
         * @description 创建任务请求。
         */
        TaskCreateRequest: {
            /** Series Id */
            series_id: number;
            /** Season Number */
            season_number: number;
            /** Episode Number */
            episode_number: number;
            /** Title */
            title: string;
            /** Source File Path */
            source_file_path: string;
            /** Cover Url */
            cover_url?: string | null;
            /** Nfo Json */
            nfo_json?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * TaskPreviewRequest
         * @description 任务路径预览请求。
         */
        TaskPreviewRequest: {
            /** Series Id */
            series_id: number;
            /** Season Number */
            season_number: number;
            /** Episode Number */
            episode_number?: number | null;
            /**
             * Title
             * @default
             */
            title: string;
            /** Source File Path */
            source_file_path: string;
            /** Cover Url */
            cover_url?: string | null;
        };
        /**
         * TaskPreviewResponse
         * @description 任务路径预览响应。
         */
        TaskPreviewResponse: {
            /** Series Id */
            series_id: number;
            /** Season Number */
            season_number: number;
            /** Episode Number */
            episode_number?: number | null;
            /** Title */
            title: string;
            /** Source File Path */
            source_file_path: string;
            /** Staging Video Path */
            staging_video_path?: string | null;
            /** Staging Nfo Path */
            staging_nfo_path?: string | null;
            /** Staging Cover Path */
            staging_cover_path?: string | null;
            /** Target Video Path */
            target_video_path?: string | null;
            /** Target Nfo Path */
            target_nfo_path?: string | null;
            /** Target Cover Path */
            target_cover_path?: string | null;
        };
        /**
         * TaskResponse
         * @description 任务响应。
         */
        TaskResponse: {
            /** Id */
            id: number;
            status: components["schemas"]["TaskStatus"];
            /** Series Id */
            series_id: number | null;
            /** Series Name */
            series_name: string | null;
            /** Emby Series Id */
            emby_series_id: string | null;
            /** Library Id */
            library_id: number | null;
            /** Library Name */
            library_name: string | null;
            /** Season Number */
            season_number: number;
            /** Episode Number */
            episode_number: number;
            /** Title */
            title: string | null;
            /** Source File Path */
            source_file_path: string | null;
            /** Staging Video Path */
            staging_video_path: string | null;
            /** Staging Nfo Path */
            staging_nfo_path: string | null;
            /** Staging Cover Path */
            staging_cover_path: string | null;
            /** Target Video Path */
            target_video_path: string | null;
            /** Target Nfo Path */
            target_nfo_path: string | null;
            /** Target Cover Path */
            target_cover_path: string | null;
            /** Nfo Json */
            nfo_json: {
                [key: string]: unknown;
            } | null;
            /** Error Message */
            error_message: string | null;
            /** Committed At */
            committed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TaskStatus
         * @description 整理任务状态机枚举。
         *
         *     取值覆盖从草稿到落地 / 失败 / 取消的完整生命周期。
         * @enum {string}
         */
        TaskStatus: "draft" | "staged" | "nfo_edited" | "ready_to_commit" | "committed" | "failed" | "cancelled";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_settings_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    put_settings_api_v1_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_emby_connection_api_v1_emby_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmbyTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmbyTestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_libraries_api_v1_emby_libraries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[];
                };
            };
        };
    };
    search_series_api_v1_emby_series_search_get: {
        parameters: {
            query: {
                /** @description 剧集搜索关键字 */
                keyword: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_series_seasons_api_v1_emby_series__series_id__seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_series_episodes_api_v1_emby_series__series_id__seasons__season_number__episodes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: string;
                season_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_series_latest_episode_api_v1_emby_series__series_id__seasons__season_number__latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: string;
                season_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatestEpisodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_libraries_api_v1_libraries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryResponse"][];
                };
            };
        };
    };
    create_library_api_v1_libraries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_library_api_v1_libraries__library_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                library_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_library_api_v1_libraries__library_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                library_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_library_api_v1_libraries__library_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                library_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_series_api_v1_series_get: {
        parameters: {
            query?: {
                library_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_series_api_v1_series_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeriesCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_series_api_v1_series__series_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_series_api_v1_series__series_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeriesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_series_api_v1_series__series_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_v1_tasks_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["TaskStatus"] | null;
                series_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_v1_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_task_api_v1_tasks_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_task_api_v1_tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_nfo_api_v1_tasks__task_id__nfo_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NFOUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_task_cover_api_v1_tasks__task_id__cover_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_task_cover_api_v1_tasks__task_id__cover_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_task_cover_api_v1_tasks__task_id__cover_download_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoverDownloadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_task_api_v1_tasks__task_id__commit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    browse_files_api_v1_files_browse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PathRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_file_api_v1_files_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PathRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
